### ISSUE TITLE
Missing styling in Preferences

### ISSUE THREAD

**Issue by cprn** [tungkradle/aseprite-than#4]
![2017-06-26-201027_751x478_scrot](https://user-images.githubusercontent.com/6132708/27553565-a3dffb50-5aab-11e7-8f80-f1d3003b48b6.png)

Aseprite (Steam) 1.2-beta10
Aseprite-than (master)

**Comment by lettdev** [comment]
Thanks for feedback, I fixed it in the latest version, which is also compatible with the new extensions system in v1.2-beta10

[https://github.com/tungkradle/aseprite-than/releases/tag/v1.2.4](https://github.com/tungkradle/aseprite-than/releases/tag/v1.2.4)

**Comment by cprn** [comment]
Confirmed.

![2017-06-28-034753_752x480_scrot](https://user-images.githubusercontent.com/6132708/27617125-9e5d5984-5bb4-11e7-9bee-24bdc1f935d3.png)
