### ISSUE TITLE
Blue corners

### ISSUE THREAD

**Issue by Brottweiler** [tungkradle/aseprite-than#5]
Notice the blue in the corner of the scroll bars, looks like it should not be there.

Than
![image](https://user-images.githubusercontent.com/1613137/47260503-25a0c200-d4bd-11e8-9887-44d71fdcfa48.png)

Default
![image](https://user-images.githubusercontent.com/1613137/47260500-1c175a00-d4bd-11e8-8844-a3a24cb56329.png)

**Comment by cprn** [comment]
Yeah, I can confirm it's there. Tested on following versions (installed from Steam on Linux):

- 1.2.9
- 1.2.10-beta4-x64

Branches 1.1.13 and 1.2-beta12 don't run for me (missing curl version) so couldn't be tested.

**Comment by lettdev** [comment]
Sorry for (very) late reply. I've been working with a new theme for a while and forgot to check. This one -> [v1.2.5](https://github.com/tungkradle/aseprite-than/releases/download/v1.2.5/than-v1.2.5.zip) should fix it.
